# Generated by Django 3.2 on 2021-04-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='posted_data',
            new_name='posted_date',
        ),
    ]
