# Generated by Django 3.2 on 2021-04-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_posted_data_record_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='post',
            field=models.TextField(),
        ),
    ]
